notebooks/batch/exportByFeat.ipynb

In 7cc033b4 the API of the batch changed.

Adapt notebook to new API

---

.github/unit.yaml

- create a unit.yaml file
- run github actions
- add tokens in the github repository settings

feat: init the CI/CD test suit

---

.github/workflows/release.yaml

build: add a release pipeline

---

docs/conf.py
docs/index.rst
geetools/Array/__init__.py
geetools/ComputedObject/__init__.py
geetools/Date/__init__.py
geetools/DateRange/__init__.py
geetools/Dictionary/__init__.py
geetools/Feature/__init__.py
geetools/FeatureCollection/__init__.py
geetools/Filter/__init__.py
geetools/Geometry/__init__.py
geetools/Image/__init__.py
geetools/ImageCollection/__init__.py
geetools/Join/__init__.py
geetools/List/__init__.py
geetools/Number/__init__.py
geetools/String/__init__.py
geetools/User/__init__.py
warnings.txt

docs: silence dynamic examples

---

README.rst
docs/_static/switcher.json
docs/conf.py

docs: add a switcher to the docs

---

docs/conf.py
noxfile.py

docs: make every class and method go into their own page

---

geetools/Asset/__init__.py
tests/test_Asset.py

- get the type as a property
- check if the asset is a project (not an asset per se but it has a path signature) 
- make iterdiv work on project as well

fix: various bug in Asset object

---

docs/conf.py

docs: show right sidebar depth by default

---

docs/usage/layout.rst
geetools/Asset/__init__.py
tests/conftest.py
tests/test_Asset.py

feat: add a copy method to the Asset object

---

geetools/Asset/__init__.py

fix: add a raised parameter to all is_something methods

---

docs/usage/layout.rst
geetools/Asset/__init__.py
tests/test_Asset.py
tests/test_Asset/test_glob.yml
tests/test_Asset/test_rglob.yml

test: add glob and rglob tests

---

geetools/Asset/__init__.py
pyproject.toml
tests/test_Asset.py

fix: add back the format_description method

---

geetools/Image/__init__.py
geetools/ImageCollection/__init__.py
tests/test_ImageCollection/test_to_xarray.yml

The issue is solved from Google side: https://issuetracker.google.com/issues/331016656

fix: stop editing the STAC dict

---

geetools/Asset/__init__.py
pyproject.toml

the method is now available in both Python and javascript API
tests are blocked by: https://issuetracker.google.com/issues/338958222

fix: use createFolder method

---

geetools/FeatureCollection/__init__.py

refactor: cm submodule has been dropped

---

README.rst

apply the workaround from https://github.com/github/markup/issues/1801

docs: make badges inlined on github

---

geetools/ImageCollection/__init__.py
geetools/tools/_deprecated_imagecollection.py
tests/test_ImageCollection.py

The work on this PR is blocked by https://issuetracker.google.com/issues/322838709.

refactor: implementation of containsBandNames

---

docs/_templates/python/module.rst
docs/usage/layout.rst
geetools/ImageCollection/__init__.py
tests/test_ImageCollection.py

When merging `contains` many issues were raised by the CI due to weird conflicts solutions. 
This PR is solving them.

fix: solve merging issue

---

.pre-commit-config.yaml

fix: migrate the pre-commit names

---

geetools/Date.py
tests/test_Date.py

implent the now constructor that should be a default behaviour TBH

feat: new now Date constructor

---

geetools/ImageCollection.py

refactor: typo in the examples

---

geetools/String.py

fix: cast result of ee.String.format to ee.String

---

docs/_static/custom.css

applying suggestions from https://github.com/pydata/pydata-sphinx-theme/issues/2017

docs: update width of the main content

---

docs/index.rst
docs/usage/index.rst
geetools/__init__.py

docs: small links updates

---

geetools/__init__.py
geetools/ee_number.py
geetools/utils.py

docs: initialize earthengine in jupyter-sphinx cells

---

docs/_templates/python/class.rst
docs/_templates/python/function.rst
docs/_templates/python/method.rst
docs/_templates/python/module.rst
geetools/ee_image_collection.py

docs: only keep the last atom in API documetnation

---

geetools/ee_date.py

docs: use the correct date format

---

CONTRIBUTING.rst

docs: update EE initialization for local dev

---

.github/workflows/unit.yaml

test: fix codecov display

---

.github/workflows/unit.yaml

testing stuff to make the codecov run work as expected and make sure the files are there again. This PR will be squashed if succesful.

build: move to codecov v5

---

geetools/ee_initialize.py

add the project_id to the service account Initialize call.

fix: add pthe project to the initialize call

---

geetools/ee_number.py
tests/test_Number.py

Fix #431 
Everything is in the title. THe methods are very straight forward nothing fancy to be honest.

feat: add a isClose and isEqual methods for numbers

---

.github/workflows/unit.yaml
pyproject.toml

This restores our compatibility with all modern version of Python

fix: move Python version u^p

---

geetools/ee_image_collection.py

refactor: avoid sorting in groupInterval

---

geetools/ee_export.py

refactor: use the index instead of converting the imageCollection into a list
