gee-community/geetools

- geetools/batch/imagecollection.py
- notebooks/batch/exportToGCS.ipynb
Dear @fitoprincipe, Dear all,
Thanks for your great work on this package! I really appreciate the work that you put in this project. It made my work on Google Earth Engine and exporting data much more enjoyable! 
I recently needed to export some image collections directly to GCS instead of my Drive.
So, I added `.toCloudStorage` to the `batch.imagecollection` functions which is based on `ee.batch.Export.image.toCloudStorage` similar to `.toDrive`. 
I tried to stay as close to the `.toDrive` function as possible. 
I added a working example as a notebook here `notebooks/batch/exportToGCS.ipynb`. This notebook was modified from `notebooks/batch/exportByFeat.ipynb`. To reproduce the results, you would need a bucket with write access and a default GCS project.
Let me know what should be …
> Added .toCloudStorage function to batch.imagecollection

- geetools/batch/imagecollection.py
FIXED `return tasklist` was missing in batch.Export.imagecollection.toCloudStorage
> -returning tasklist

- .github/workflows/unit.yaml
- geetools/Array/__init__.py
- geetools/ComputedObject/__init__.py
- geetools/Date/__init__.py
- geetools/DateRange/__init__.py
- geetools/Dictionary/__init__.py
- geetools/FeatureCollection/__init__.py
- geetools/Image/__init__.py
- geetools/ImageCollection/__init__.py
- geetools/Join/__init__.py
- geetools/List/__init__.py
- geetools/Number/__init__.py
- geetools/String/__init__.py
- geetools/User/__init__.py
- geetools/accessors.py
- geetools/types.py
- pyproject.toml
- test.ipynb
Fix #128 
take advantage of this to make mypy happy and reintroduce it into the pipelines
> refactor: use custom types

- geetools/Asset/__init__.py
- tests/test_Asset.py
Fix #231 
As mentioned in the issue a user should not be able to register an absolute path as it has no GEE meaning. 
To prevent that any trailing "/" will be removed upon Asset init.
> fix: prevent Asset to be absolute

- geetools/Image/__init__.py
`ee.Projection` not only stores the CRS but also the nominal scale, and although the CRS is usually constant across all bands, is not the same for the nominal scale (example [here](https://code.earthengine.google.com/86d798c3bee32855b5cbfb24d92037f2)). So, one of the modification of this PR is to copy each band's projection to the image generated by `ee.Image.fullLike`.
In the previous version of `fullLike` the footprint of the original images was passed to the resulting image. Now the user can choose whether to copy it or not, giving more flexibility to the user.
> enhance ee.Image.fullLike

- geetools/Image/__init__.py
I tried to use an `ee.Image` created by `ee.Image.geetools.fullLike` (with the latest modifications) inside an `ee.ImageCollection` and got an error complaining about "not being an homogeneous" collection. This PR solves that issue.
> fix fullLike (again)

- docs/usage/layout.rst
- geetools/Asset/__init__.py
- tests/test_Asset.py
Fix #274 
The side step from the original vanilla method is that I'm using kwargs instead of a dict. 
My reasoning is that a dict is not the easiest to write in Python linted code as you'll get a double indentation for nothing.
> feat: add a setProperty method to the Asset object

- docs/usage/layout.rst
- geetools/Array/__init__.py
- geetools/DateRange/__init__.py
- geetools/__init__.py
- pyproject.toml
- tests/test_Array.py
- tests/test_DateRange.py
FIx #206 
Fix #173 
Fix #290 
I finally can rely on the static definition of all GEE classes.
> fix: use the fuly static definition of GEE

- docs/conf.py
The edit in github button, available on all pages was still pointing to the old "master" branch making it impossible to reach the appropriate page from the documentation when a small edit was needed.
> docs: fix edit in github link

- docs/_static/banner.html
- docs/conf.py
> docs: add a single banner shared in all published documentation

- geetools/Asset.py
> refactor: avoid deprecation notices

- docs/usage/index.rst
Commit b03f6100bd4f0cdd36d522fb8213bf4b817dc5d2 changed the location of `template.ipynb`. This PR adjusts sources to changes.
> fix: update template notebook

- geetools/Asset.py
> fix: if no value is provided, use the root asset folder

- tests/test_Export.py
The export task timeout when to many tests are run at the same time reason why the number of images in the created asset is changing when multiple tests are run at the same time. I'm reluctant for now to increase the timout value so I'll wait for a better idea.
> test: skip the export test

- geetools/ee_profiler.py
I found out that sometimes the profiler returns `CurrMem` and sometimes it doesn't. If it does, the indices change, so instead of adding a lot of conditionals, I decided to create a mapping for headers and functions to process each header.
To fix https://github.com/gee-community/geetools/issues/375
> Fix profiler

- geetools/ee_feature_collection.py
- tests/test_FeatureCollection.py
- tests/test_FeatureCollection/test_to_dictionary.yml
https://github.com/gee-community/geetools/pull/368#pullrequestreview-2412434217
> `ee.FeatureCollection` to `ee.Dictionary`

- geetools/ee_asset.py
Fix #371 
It was much more complicated than I though. 
Setting the `system:time_start` of the ImageCollection is forcing me to jump in 3 differnet naming convention: 
- `startTime` in the `getAsset` method
- `start_time` in the `updateAsset` method 
- `system:time_start` (still camel case but reversed) in `ee.imageCollection.propertynames`
In this PR I upgraded the `setProperties` so it supports all type of properties (system and normal) and tay consistent with the server API convention (system:time_start).
I then added extra steps in the `copy` method to retreive `startTime` from the original asset and pass it in the correct format. 
I also reported my findings on the Google issue tracker: https://issuetracker.google.com/issues/381535044
> fix: copy the metadata of the ImageCollection when copying an asset

- docs/_templates/python/class.rst
- docs/_templates/python/function.rst
- docs/_templates/python/method.rst
- docs/_templates/python/module.rst
As there is 1 single item per file this is basically useless. Also as the source is auto-generated by the docstring, the "edit on github" button is not pointing to an existing file.
> docs: remove left side bar in API reference

- geetools/ee_feature_collection.py
- tests/test_FeatureCollection.py
- tests/test_FeatureCollection/test_from_geo_interface.yml
- tests/test_FeatureCollection/test_from_geo_interface_from_dict.yml
> feat: create a featureCollection from a geointerface

- geetools/ee_feature_collection.py
Fix #384 
We were filtering out the system properties so on the fly generated FeatureCollection including property less features were crashing (as their only property was "system:index"). 
This PR is reordering the properties: 
- first the named properties 
- then the system one 
This maintains compatibility with older implementation (do your select before calling `plot`) and guarantees it's going to work with the propertyless features.
> fix: add back the system properties

- .gitignore
- docs/setup/pattern.rst
- geetools/accessors.py
- geetools/ee_array.py
- geetools/ee_asset.py
- geetools/ee_authenticate.py
- geetools/ee_computed_object.py
- geetools/ee_date.py
- geetools/ee_date_range.py
- geetools/ee_dictionary.py
- geetools/ee_export.py
- geetools/ee_feature.py
- geetools/ee_feature_collection.py
- geetools/ee_filter.py
- geetools/ee_geometry.py
- geetools/ee_image.py
- geetools/ee_image_collection.py
- geetools/ee_initialize.py
- geetools/ee_join.py
- geetools/ee_list.py
- geetools/ee_number.py
- geetools/ee_profiler.py
- geetools/ee_string.py
- geetools/utils.py
I realised that many methods have some bugs in their documentation. For instance, [`getOffsetParams`](https://geetools.readthedocs.io/en/stable/autoapi/geetools/ee_image/ImageAccessor.getOffsetParams.html) has an example which is not well idented.
This PR aims to fix these errors in the documentation.
The changes are:
- Fix a lot of typos in documentation.
- Improve the identation along the methods' documentation.
- Update examples to the new version (from `ee.ImageCollection(‘COPERNICUS/S2_SR’).first().getSTAC()` to `ee.ImageCollection(‘COPERNICUS/S2_SR’).first().geetools.getSTAC()`).
- Improve typing (for example, `getScaleParams` returns a `dict`, instead of `dict[str, float]` that is the complete typing, or update the wrong typing `ee.image` to `ee.Image`).
- Extend documentation to …
> docs: Fix documentation

- geetools/ee_dictionary.py
- tests/test_Dictionary.py
- tests/test_Dictionary/test_to_table_any.yml
- tests/test_Dictionary/test_to_table_dict.yml
- tests/test_Dictionary/test_to_table_list.yml
https://github.com/gee-community/geetools/pull/368#pullrequestreview-2412434217
> `ee.Dictionary` to `ee.FeatureCollection`

- geetools/ee_authenticate.py
- geetools/ee_feature.py
- geetools/ee_feature_collection.py
- geetools/ee_image.py
- geetools/ee_image_collection.py
- geetools/ee_initialize.py
- geetools/utils.py
With respect the PR #409 
> > Some methods uses mutable parameters, for example
> 
> We realized that wih Rodrigo some time ago, I would suggest to do it in a follow-up PR
I mentioned that are many mutable parameters. This is the follow-up PR to fix it.
The changes are:
* Improve typing: The list are more specific and the paths can be a Path instance.
* Drop mutable default arguments: Replace empty list with Nones
* Convert a method in static if the method doesn't use anything.
> refactor: improve typing and delete mutable default arguments

- geetools/ee_date.py
- tests/test_Date.py
Luckily I live in a different time zone than UTC and tests for this method was failing due to it.
I follow the GEE pattern as `ee.Date.format` method, to which user can pass a time zone and get the formatted representation of that date in the specified time zone (https://code.earthengine.google.com/91d328471a218815afda4309021dc68a)
> add timezone to ee.Date conversion to datetime

- geetools/ee_image_collection.py
- tests/conftest.py
- tests/test_ImageCollection.py
In some image collections the images contain all bands but some are completely masked out. In this case, using the band names is useless and mosaicking will not fail, but the user could still want to use valid bands and avoid the masked ones.
There are 2 changes:
1. Use already computed system property `system:band_names` instead of computing it on the fly and storing in a property with random name.
2. Allow the user to specify the name of the property that contains the band names.
> `ImageCollection.containsBandNames`: add argument to indicate the property that contains the band names

- geetools/ee_export.py
Fix #433 
everything is in the title
> docs: typo in examples

- geetools/ee_date.py
- tests/test_Date.py
Everything is in the title. 
- The `toDOY` method is transforming any doy value into it's corresponding 0 -365 range equivalent. the 60th day (29th of february) will only appear during leap year.
- The `fromDOY` ethod will now only expect this type of entry to generate a date. 
Tests have been updated accodingly. 
This feature is needed for imagecollection plotting and year to year  (eason to season) comparaisons.
> feat: add year agnostic doy capacity

- geetools/ee_feature_collection.py
- tests/test_FeatureCollection.py
- tests/test_FeatureCollection/serialized_test_column_names.yml
- tests/test_FeatureCollection/test_column_names.yml
Sometime all `Feature` from a `FeatureCollection` do not contain the same properties, thus getting the "column" names is unintuitive, because this doesn't work: `fc.first().propertyNames()` and we might not want to call `getInfo`.
The test is showing a clear example on when this happens and proves that this method manages to get all column names.
> get name of 'columns' from a FeatureCollection

- geetools/ee_asset.py
everything is in the title THis was not working because number from GEE are always interpreted as floats: 
```python 
ic = ee.ImageCollection(collection.as_posix())
collection.setProperties(**{
"system:time_start": ic.aggregate_min("system:time_start").getInfo(),
"system:time_end": ic.aggregate_max("system:time_start").getInfo(),
})
```
This PR should make sure the numbers are alwaysinterpreted as timestamps and transformed into str isoformated dates
> fix: data can be a float as well
